### ISSUE TITLE
Is it build for 64bit?

### ISSUE THREAD

**Issue by caspahouzer** [viezel/NappAppearance#13]

**Comment by bablydas** [comment]
Can we have new version to support 64 bit? Thanks

**Comment by twustep** [comment]
I tried to recompile it in 64bit but it caused some bugs. Hoping we can get a version directly from viezel.

**Comment by mrlundis** [comment]
I've made a 64bit build, and it works well enough for our use cases. What kind of bugs did you see @twustep?

**Comment by darkhorse2013** [comment]
@mrlundis alloy does not pick up the new module v1.3.0

I do modules > iphone > dk.napp.appearance > 1.3.0

then go to tiapp > add new module, not on the list

**Comment by mrlundis** [comment]
@darkhorse2013 If you already use an earlier version of the module, you will need to change the version for your existing module import instead. 

Otherwise try adding the module manually, as described here:
https://github.com/viezel/NappAppearance#referencing-the-module-in-your-titanium-mobile-application

**Comment by darkhorse2013** [comment]
@mrlundis  by changing the version for your existing module, do you mean rename the folder and replace the files with yours?

**Comment by mrlundis** [comment]
@darkhorse2013 No, I ment in the tiapp.xml file. If the module has a specified version you'll need to change it to 1.3.0 (or remove the version attribute entirely.)

**Comment by darkhorse2013** [comment]
Thanks , works great! it didn't build because I didn't set the sdk to titanium 3.5

**Comment by twustep** [comment]
Hi @mrlundis, sorry for the delay, here are the issues we found.

(I have yet to try the methods specified in this thread, perhaps that will fix the issues)

1. The window titles are now always black and they can't be controlled
2. 1px strokes are now thicker (this may be due to something else in our app, so don't pay much attention to this one)

See pdf for visual:

http://cl.ly/1t213R0E3c3M

**Comment by mrlundis** [comment]
@twustep Have you tried setting the title styling using the titleAttributes property instead?
http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.Window-property-titleAttributes

(Those settings should possibly also be removed from tis module..)

**Comment by caspahouzer** [comment]
I did a pull request: https://github.com/viezel/NappAppearance/pull/14

It is now build for 64 bit

**Comment by twustep** [comment]
Thanks #mrlundis, I ended up using your suggestion and it works. 

The bit64 plugin still messes with problem #2 in my previous comment, but it is something I can (will have to) live with, since the plugin works great in every other aspect.

Thanks again!
m
